version: "3.8"
services:
  postgres-resume-db:
    image: postgres:15
    container_name: postgres_container_resume
    restart: always
    environment:
      POSTGRES_DB: resumes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - '5432:5432'